# Generated by Django 2.0.5 on 2018-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('size', models.IntegerField(default=1)),
                ('syrup', models.CharField(max_length=30)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('ordered_at', models.DateTimeField(verbose_name="order's date")),
                ('coffee', models.ForeignKey(on_delete=None, to='bot.Coffee')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('coffee_id', models.ForeignKey(on_delete=None, related_name='+', to='bot.Coffee')),
            ],
        ),
        migrations.CreateModel(
            name='Syrup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.IntegerField(default=0)),
                ('emoji', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='syrup',
            field=models.ForeignKey(on_delete=None, to='bot.Syrup'),
        ),
    ]
