# Generated by Django 2.0.6 on 2018-06-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20180608_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='coffee_id',
            new_name='coffee',
        ),
    ]
