# Generated by Django 2.0.6 on 2018-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20180609_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='size',
            field=models.ForeignKey(on_delete=None, to='bot.Size'),
        ),
    ]
