# Generated by Django 2.0.6 on 2018-06-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20180610_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='coffee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Coffee'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Size'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='syrup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Syrup'),
        ),
        migrations.AlterField(
            model_name='size',
            name='coffee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bot.Coffee'),
        ),
    ]
